backend:
  name: github
  repo: Geek-I-Am/articles
publish_mode: editorial_workflow
site_url: https://geekiam.io
logo_url: https://geekiam.io/uploads/geekiam-logo.png
display_url: https://geekiam.io
show_preview_links: true
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: geekiam-io
    api_key: 775599314677177
collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true }
      - label: 'Info'
        name: 'info'
        widget: 'object'
        fields:
          [
            { label: 'Title', name: 'title', widget: 'string', required: true },
            { label: 'Description', name: 'description', widget: 'string', required: true },
            { label: 'Summary', name: 'summary', widget: 'markdown', required: true },
            { label: 'Publish Date', name: 'publishDate', widget: 'date', required: true},
            { label: 'Feature image path', name: 'feature', widget: 'string', required: true},
            { label: 'Author', name: 'author', widget: 'object',
              fields:
                [
                  { label: 'Firstname', name: 'firstName', widget: 'string', required: true },
                  { label: 'Lastname', name: 'lastName', widget: 'string', required: true },
                  { label: 'Github Username', name: 'github', widget: 'string', required: true }
                ]
            },
            { label: 'Keywords', name: 'keywords',  widget: list,
              field: { label: 'keyword', name: 'keyword', widget: 'string' }
            }
          ]
      - label: 'Twitter'
        name: 'twitter'
        widget: 'object'
        fields:
          [
            { label: 'Title', name: 'title', widget: 'string', required: true },
            { label: 'Description', name: 'description', widget: 'string', required: true },
            { label: 'Site', name: 'site', widget: 'select', required: true, options: ['geekiam1', 'threenine39']},
            { label: 'Username', name: 'username', widget: 'select', required: true, options: ['gary_woodfine', 'threenine39']},
            { label: 'Card Image', name: 'cardImage', widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'select', options: ['git-tutorials.jpg', 'code-tutorials.png', 'javascript-tutorials.png', 'code-tutorials-2.png', 'vue-tutorials.png'] },
                  { label: 'alt', name: 'alt', widget: 'string' }
                ]
            }
          ]
      - label: "Tags"
        name: "tags"
        widget: list
        field: { label: "Tag", name: "tag", widget: "string" }
      - {label: "Body", name: "body", widget: "markdown" }
